#!/bin/sh
python generator_binary_generic.py simd_binary_arithmetic_generic.hpp
python generator_binary_sse.py simd_binary_arithmetic_sse.hpp
python generator_binary_fallbacks.py simd_binary_arithmetic_fallbacks_float.hpp simd_binary_arithmetic_fallbacks_double.hpp

python generator_unary_generic.py simd_unary_arithmetic_generic.hpp
python generator_unary_fallbacks.py simd_unary_arithmetic_fallbacks_float.hpp simd_unary_arithmetic_fallbacks_double.hpp
